theme: jekyll-theme-minimal
title: Cyrill Rafael Vasilyev
description: Artwork showcase

url: www.cyrillrafael.com
# Permalinks
permalink: /:title/

# Navigation links
nav_links:
  - title: Paintings
    url: /paintings
  - title: Prints
    url: /prints
  - title: About
    url: /about
  - title: CV
    url: /cv
  - title: Instagram
    url: https://www.instagram.com/cyrillrafael/
  - title: Telegram
    url: https://t.me/+31686218199/

redirects:
  - www.cyrillrafael.com: /paintings
