title: Cyrill Rafael Vasilyev
description: Artwork showcase
theme: null

url: www.cyrillrafael.com
# Permalinks
permalink: /:title/

# Navigation links
nav_links:
  - title: Paintings
    url: /paintings
  - title: Linocuts
    url: /linocuts
  - title: About
    url: /about
  - title: CV
    url: /cv
  - title: Instagram
    url: https://www.instagram.com/cyrillrafael/
    icon: fas fa-instagram
  - title: Telegram
    url: https://t.me/+31686218199/
    icon: far fa-telegram

# Redirects
redirects:
  - from: "/"
    to: "/paintings/"
