# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: /uprootiny.github.io
title: Cyrill Rafael Vasilyev
email: olenisinelo@gmail.com
description: Cyrill Rafael Art
# twitter_username: 
github_username: olenisinelo

minimal_mistakes_skin: default #FIXME
search: false

# Build settings
markdown: kramdown #FIXME
remote_theme: mmistakes/minimal-mistakes #FIXME
# Outputting

# include:
#   - _pages
include: ["_pages"]



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  # - jekyll-feed
  - jemoji
  - jekyll-include-cache

# author:
#   name   : "Cyrill Rafael Vasilyev"
#   #avatar : "uprootiny/uprootiny.github.io/gallery/AAA_9.jpg"
#   avatar : "/gallery/AAA_9.jpg"
#   bio    : "•"
#   links:
#     - label: "Website"
#       url: "https://cyrillrafael.wordpress.com/#jp-carousel-38"
#       icon: "fas fa-fw fa-picture-o"
#       url: "https://www.cyrillrafael.com"
#     # - label: "Twitter"
#     #   icon: "fab fa-fw fa-twitter-square"
#     #   url: "https://twitter.com/"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-github"
#       url: "https://github.com/olenisinelo"
#     - label: "GitHub"
#       icon: "fab fa-fw fa-telegram"
#       url: "https://github.com/olenisinelo"
#     - label: "Instagram"
#       icon: "fab fa-fw fa-instagram"
#       url: "https://instagram.com/olenisinelo"
#     - label: "Photos"
#       icon: "fas fa-fw fa-camera-retro"
#       url: "https://instagram.com/olenisinelo"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/uprootiny/uprootiny.github.io"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/olenisinelo"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "tel:// +31 6 86 21 81 99"


defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _images
  - scope:
      path: "assets/images"
      type: pages
    values:
      layout: single
      author_profile: true

painting_archive:
  type: liquid
  path: /paintings/
